/* tslint:disable */
/* eslint-disable */
/**
 * Goovi ID
 * GOOVI ID Website spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCompress,
  CreateTranscode,
  TranscodeQueue,
} from '../models';
import {
    CreateCompressFromJSON,
    CreateCompressToJSON,
    CreateTranscodeFromJSON,
    CreateTranscodeToJSON,
    TranscodeQueueFromJSON,
    TranscodeQueueToJSON,
} from '../models';

export interface CompressPostRequest {
    createCompress?: CreateCompress;
}

export interface TranscodeDeleteRequest {
    id?: string;
}

export interface TranscodeGetRequest {
    id?: string;
}

export interface TranscodePostRequest {
    createTranscode?: CreateTranscode;
}

/**
 * 
 */
export class TranscodeApi extends runtime.BaseAPI {

    /**
     * Create Compress
     */
    async compressPostRaw(requestParameters: CompressPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = this.configuration.apiKey("X-API-KEY"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/compress`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCompressToJSON(requestParameters.createCompress),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create Compress
     */
    async compressPost(requestParameters: CompressPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.compressPostRaw(requestParameters, initOverrides);
    }

    /**
     * Cancel Queue
     */
    async transcodeDeleteRaw(requestParameters: TranscodeDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters.id !== undefined) {
            queryParameters['id'] = requestParameters.id;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Refresh authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Token authentication
        }

        const response = await this.request({
            path: `/transcode`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Cancel Queue
     */
    async transcodeDelete(requestParameters: TranscodeDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.transcodeDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get a transcode
     */
    async transcodeGetRaw(requestParameters: TranscodeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TranscodeQueue>> {
        const queryParameters: any = {};

        if (requestParameters.id !== undefined) {
            queryParameters['id'] = requestParameters.id;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Refresh authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Token authentication
        }

        const response = await this.request({
            path: `/transcode`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TranscodeQueueFromJSON(jsonValue));
    }

    /**
     * Get a transcode
     */
    async transcodeGet(requestParameters: TranscodeGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TranscodeQueue> {
        const response = await this.transcodeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Queue
     */
    async transcodePostRaw(requestParameters: TranscodePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Refresh authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Token authentication
        }

        const response = await this.request({
            path: `/transcode`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTranscodeToJSON(requestParameters.createTranscode),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create Queue
     */
    async transcodePost(requestParameters: TranscodePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.transcodePostRaw(requestParameters, initOverrides);
    }

    /**
     * Get list transcode
     */
    async transcodesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TranscodeQueue>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Refresh authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Token authentication
        }

        const response = await this.request({
            path: `/transcodes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TranscodeQueueFromJSON));
    }

    /**
     * Get list transcode
     */
    async transcodesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TranscodeQueue>> {
        const response = await this.transcodesGetRaw(initOverrides);
        return await response.value();
    }

}
