/* tslint:disable */
/* eslint-disable */
/**
 * Goovi ID
 * GOOVI ID Website spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DepositModel
 */
export interface DepositModel {
    /**
     * 
     * @type {number}
     * @memberof DepositModel
     */
    requestAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof DepositModel
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof DepositModel
     */
    tax?: number;
    /**
     * 
     * @type {string}
     * @memberof DepositModel
     */
    depositId?: string;
    /**
     * 
     * @type {string}
     * @memberof DepositModel
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof DepositModel
     */
    midtransToken?: string;
    /**
     * 
     * @type {Date}
     * @memberof DepositModel
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the DepositModel interface.
 */
export function instanceOfDepositModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DepositModelFromJSON(json: any): DepositModel {
    return DepositModelFromJSONTyped(json, false);
}

export function DepositModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepositModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'requestAmount': !exists(json, 'request_amount') ? undefined : json['request_amount'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'tax': !exists(json, 'tax') ? undefined : json['tax'],
        'depositId': !exists(json, 'deposit_id') ? undefined : json['deposit_id'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'midtransToken': !exists(json, 'midtrans_token') ? undefined : json['midtrans_token'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
    };
}

export function DepositModelToJSON(value?: DepositModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'request_amount': value.requestAmount,
        'amount': value.amount,
        'tax': value.tax,
        'deposit_id': value.depositId,
        'status': value.status,
        'midtrans_token': value.midtransToken,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
    };
}

