/* tslint:disable */
/* eslint-disable */
/**
 * Goovi ID
 * GOOVI ID Website spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DepositRequest
 */
export interface DepositRequest {
    /**
     * 
     * @type {number}
     * @memberof DepositRequest
     */
    requestAmount?: number;
}

/**
 * Check if a given object implements the DepositRequest interface.
 */
export function instanceOfDepositRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DepositRequestFromJSON(json: any): DepositRequest {
    return DepositRequestFromJSONTyped(json, false);
}

export function DepositRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepositRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'requestAmount': !exists(json, 'request_amount') ? undefined : json['request_amount'],
    };
}

export function DepositRequestToJSON(value?: DepositRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'request_amount': value.requestAmount,
    };
}

