/* tslint:disable */
/* eslint-disable */
/**
 * Goovi ID
 * GOOVI ID Website spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageInfo
 */
export interface ImageInfo {
    /**
     * 
     * @type {string}
     * @memberof ImageInfo
     */
    imageType?: string;
    /**
     * 
     * @type {number}
     * @memberof ImageInfo
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof ImageInfo
     */
    height?: number;
}

/**
 * Check if a given object implements the ImageInfo interface.
 */
export function instanceOfImageInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ImageInfoFromJSON(json: any): ImageInfo {
    return ImageInfoFromJSONTyped(json, false);
}

export function ImageInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'imageType': !exists(json, 'image_type') ? undefined : json['image_type'],
        'width': !exists(json, 'width') ? undefined : json['width'],
        'height': !exists(json, 'height') ? undefined : json['height'],
    };
}

export function ImageInfoToJSON(value?: ImageInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image_type': value.imageType,
        'width': value.width,
        'height': value.height,
    };
}

