/* tslint:disable */
/* eslint-disable */
/**
 * Goovi ID
 * GOOVI ID Website spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SocialLoginReq
 */
export interface SocialLoginReq {
    /**
     * 
     * @type {string}
     * @memberof SocialLoginReq
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof SocialLoginReq
     */
    appsource?: string;
}

/**
 * Check if a given object implements the SocialLoginReq interface.
 */
export function instanceOfSocialLoginReq(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SocialLoginReqFromJSON(json: any): SocialLoginReq {
    return SocialLoginReqFromJSONTyped(json, false);
}

export function SocialLoginReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocialLoginReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': !exists(json, 'token') ? undefined : json['token'],
        'appsource': !exists(json, 'appsource') ? undefined : json['appsource'],
    };
}

export function SocialLoginReqToJSON(value?: SocialLoginReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'appsource': value.appsource,
    };
}

