/* tslint:disable */
/* eslint-disable */
/**
 * Goovi ID
 * GOOVI ID Website spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamInvitatioUserResponse
 */
export interface TeamInvitatioUserResponse {
    /**
     * 
     * @type {string}
     * @memberof TeamInvitatioUserResponse
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TeamInvitatioUserResponse
     */
    response?: boolean;
}

/**
 * Check if a given object implements the TeamInvitatioUserResponse interface.
 */
export function instanceOfTeamInvitatioUserResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeamInvitatioUserResponseFromJSON(json: any): TeamInvitatioUserResponse {
    return TeamInvitatioUserResponseFromJSONTyped(json, false);
}

export function TeamInvitatioUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamInvitatioUserResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'response': !exists(json, 'response') ? undefined : json['response'],
    };
}

export function TeamInvitatioUserResponseToJSON(value?: TeamInvitatioUserResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'response': value.response,
    };
}

