/* tslint:disable */
/* eslint-disable */
/**
 * Goovi ID
 * GOOVI ID Website spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamSnippet
 */
export interface TeamSnippet {
    /**
     * 
     * @type {string}
     * @memberof TeamSnippet
     */
    teamID?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamSnippet
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamSnippet
     */
    teamOwnerID?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamSnippet
     */
    avatarurl?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamSnippet
     */
    badge?: string;
}

/**
 * Check if a given object implements the TeamSnippet interface.
 */
export function instanceOfTeamSnippet(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeamSnippetFromJSON(json: any): TeamSnippet {
    return TeamSnippetFromJSONTyped(json, false);
}

export function TeamSnippetFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamSnippet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'teamID': !exists(json, 'teamID') ? undefined : json['teamID'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'teamOwnerID': !exists(json, 'teamOwnerID') ? undefined : json['teamOwnerID'],
        'avatarurl': !exists(json, 'avatarurl') ? undefined : json['avatarurl'],
        'badge': !exists(json, 'badge') ? undefined : json['badge'],
    };
}

export function TeamSnippetToJSON(value?: TeamSnippet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'teamID': value.teamID,
        'name': value.name,
        'teamOwnerID': value.teamOwnerID,
        'avatarurl': value.avatarurl,
        'badge': value.badge,
    };
}

