/* tslint:disable */
/* eslint-disable */
/**
 * Goovi ID
 * GOOVI ID Website spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TranscodeError
 */
export interface TranscodeError {
    /**
     * 
     * @type {string}
     * @memberof TranscodeError
     */
    errorType?: string;
    /**
     * 
     * @type {string}
     * @memberof TranscodeError
     */
    errorCause?: string;
    /**
     * 
     * @type {Date}
     * @memberof TranscodeError
     */
    errorAt?: Date;
}

/**
 * Check if a given object implements the TranscodeError interface.
 */
export function instanceOfTranscodeError(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TranscodeErrorFromJSON(json: any): TranscodeError {
    return TranscodeErrorFromJSONTyped(json, false);
}

export function TranscodeErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranscodeError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorType': !exists(json, 'error_type') ? undefined : json['error_type'],
        'errorCause': !exists(json, 'error_cause') ? undefined : json['error_cause'],
        'errorAt': !exists(json, 'error_at') ? undefined : (new Date(json['error_at'])),
    };
}

export function TranscodeErrorToJSON(value?: TranscodeError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error_type': value.errorType,
        'error_cause': value.errorCause,
        'error_at': value.errorAt === undefined ? undefined : (value.errorAt.toISOString()),
    };
}

