/* tslint:disable */
/* eslint-disable */
/**
 * Goovi ID
 * GOOVI ID Website spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TranscodeMeta
 */
export interface TranscodeMeta {
    /**
     * 
     * @type {Date}
     * @memberof TranscodeMeta
     */
    processStartAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TranscodeMeta
     */
    processEndAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof TranscodeMeta
     */
    processDuration?: number;
    /**
     * 
     * @type {Date}
     * @memberof TranscodeMeta
     */
    transcodeStartAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TranscodeMeta
     */
    transcodeEndAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof TranscodeMeta
     */
    transcodeDuration?: number;
}

/**
 * Check if a given object implements the TranscodeMeta interface.
 */
export function instanceOfTranscodeMeta(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TranscodeMetaFromJSON(json: any): TranscodeMeta {
    return TranscodeMetaFromJSONTyped(json, false);
}

export function TranscodeMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranscodeMeta {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'processStartAt': !exists(json, 'process_start_at') ? undefined : (new Date(json['process_start_at'])),
        'processEndAt': !exists(json, 'process_end_at') ? undefined : (new Date(json['process_end_at'])),
        'processDuration': !exists(json, 'process_duration') ? undefined : json['process_duration'],
        'transcodeStartAt': !exists(json, 'transcode_start_at') ? undefined : (new Date(json['transcode_start_at'])),
        'transcodeEndAt': !exists(json, 'transcode_end_at') ? undefined : (new Date(json['transcode_end_at'])),
        'transcodeDuration': !exists(json, 'transcode_duration') ? undefined : json['transcode_duration'],
    };
}

export function TranscodeMetaToJSON(value?: TranscodeMeta | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'process_start_at': value.processStartAt === undefined ? undefined : (value.processStartAt.toISOString()),
        'process_end_at': value.processEndAt === undefined ? undefined : (value.processEndAt.toISOString()),
        'process_duration': value.processDuration,
        'transcode_start_at': value.transcodeStartAt === undefined ? undefined : (value.transcodeStartAt.toISOString()),
        'transcode_end_at': value.transcodeEndAt === undefined ? undefined : (value.transcodeEndAt.toISOString()),
        'transcode_duration': value.transcodeDuration,
    };
}

